# Site settings
baseURL = "https://dramirna.com"
languageCode = "pt-BR"
title = "Site da Dra. Mirna"
theme = "hugo-split-theme-master"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2021 André Hiroshi Koga"

[params]

  # Metadata for search engines and social sharing
  author = "Mirna Akemi Koga"
  description = "Dra. Mirna Koga, pediatra"
  shareImage = "images/screenshot.png"
  twitterHandle = "by_koga"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/mirna.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Agendar"

      [[params.links.list1.link]]
        text = "Doctoralia"
        url = "https://www.doctoralia.com.br/mirna-koga/pediatra/guarulhos?gclid=CjwKCAiAv_KMBhAzEiwAs-rX1L876v0JhQ15ELIQe-yS2nbGtCOl2CuyQ9aebJijWKCXVMJRRcdcoBoCz24QAvD_BwE"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Endereço"

      [[params.links.list3.link]]
        text = "Rua Luiz Turri"
        url = "https://goo.gl/maps/zx9X3micxAPPrtcdA"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
